#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "devlake.fullname" . }}-external-secret
  labels:
    {{- include "devlake.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  data:
    {{- if .Values.externalSecrets.remoteRefs.dbPassword }}
    {{- if eq .Values.database.type "mysql" }}
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.dbPassword }}
    {{- else if eq .Values.database.type "postgresql" }}
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.dbPassword }}
    {{- end }}
    {{- end }}
    {{- if and (eq .Values.database.type "mysql") .Values.externalSecrets.remoteRefs.dbRootPassword }}
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.dbRootPassword }}
    {{- end }}
    {{- if .Values.externalSecrets.remoteRefs.encryptionSecret }}
    - secretKey: ENCRYPTION_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.encryptionSecret }}
    {{- end }}
    {{- if and .Values.ui.basicAuth.enabled .Values.externalSecrets.remoteRefs.uiPassword }}
    - secretKey: ADMIN_USER
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.uiPassword }}
        property: username
    - secretKey: ADMIN_PASS
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.uiPassword }}
        property: password
    {{- end }}
{{- end }}
