name: validate image and chart version
on:
  pull_request:
    branches:
      - main
    paths:
      - charts/**
jobs:
  check:
    name: validate image and chart version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install yq
        run: echo yq should already in github ubuntu-latest
      - name: chart version align with image version
        run: |
          set -e
          chart_version_text=$(yq .version ${GITHUB_WORKSPACE}/charts/devlake/Chart.yaml)
          image_version_text=$(yq .imageTag ${GITHUB_WORKSPACE}/charts/devlake/values.yaml)
          if [[ v$chart_version_text != $image_version_text ]] ; then
            echo chart version $chart_version_text is not equal to devlake version $image_version_text
            exit 1
          else 
            echo all images version are equal to chart version
          fi
